### ISSUE TITLE
Opus frameDuration defaults are incorrect

### ISSUE THREAD

**Issue by anonymousthing** [Geo1088/listen.moe-streaming-bot#6]
I've encountered an issue where the expected buffer size when encoding into Opus from the PCM stream is incorrect. Eris's VoiceConnection.js creates its stream with a frameDuration of 60, but doesn't supply this to the Opus codec, which defaults to 20. 

This results in a "RangeError: Buffer is too large". The fix is to change line 31 on Opus.js (under node_modules\eris\deps\opusscript\Opus.js) to `this.frameDuration = frameDuration || 60;`.

Is this reproducible on anybody else's versions? I've tested this on both my desktop and laptop on fresh node installs and found it occurred.

**Comment by Geo1088** [comment]
Wow, that's a good catch! Could you go ahead and PR this for me? I'll be away from my computer for the bulk of the day today.

**Comment by anonymousthing** [comment]
I'm not sure what the best way to do this would be, since it's an issue in a dependency (Eris) and not in this project. Google doesn't seem to come up with anyone else having this issue either...

**Comment by Geo1088** [comment]
Ah, sweet. Yeah the dev branch of Eris can be pretty unstable, Abal's working on a lot of voice stuff now iirc. Thanks for hunting him down for me man.

(Initially I couldn't remember if this was a dep or not, because in an earlier version of this project I re-implemented the encoder functions from Eris to make it work. Now that I use the dep directly though, you're right, it goes there.)
